# Generated by Django 5.1.1 on 2024-09-19 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Title of blog post')),
                ('content', models.TextField()),
                ('image', models.ImageField(upload_to='media/blog')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('tag', models.ManyToManyField(to='blog.tag')),
            ],
        ),
    ]
