# Generated by Django 5.1.1 on 2024-09-24 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comment_full_name_comment_website_alter_comment_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='full_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
