# Generated by Django 5.1.1 on 2024-09-24 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_comment_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.SlugField(default='', editable=False, unique=True),
            preserve_default=False,
        ),
    ]
