# Generated by Django 5.1.1 on 2024-09-23 08:28

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_blog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='AboutUs'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='Gallery'),
        ),
    ]
