# Generated by Django 5.1.1 on 2024-09-23 13:32

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_clientmessage_alter_whosme_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Text'),
        ),
    ]
